name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Assuming your dependencies are listed in a requirements.txt file
          pip install openai  # Install OpenAI library

      - name: Run your Python script
        run: |
          python your_script.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
